apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::556811045849:role/deploy_role
      username: deploy_role
      groups:
        - system:masters
