apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: ${DEPLOY_ROLE_ARN}
      username: deploy_role
      groups:
        - system:masters
