apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: blue-app
  name: blue-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blue-app
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: blue-app
    spec:
      containers:
        - image: 556811045849.dkr.ecr.eu-west-2.amazonaws.com/nginx_ds:$IMAGE_TAG
          name: blue-container
          imagePullPolicy: Always
          resources: {}
          env:
            - name: DEPLOY_TYPE
              value: $TYPE
            - name: DEPLOY_COLOR
              value: $TYPE
          ports:
            - name: web
              containerPort: 80
              protocol: TCP
status: {}
