apiVersion: v1
kind: Service
metadata:
  name: service-deploy
  labels:
    app: deploy-demo
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: web
  selector:
    app: deploy-demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: deploy-demo
  name: deployment-demo-$DEPLOY_TYPE
spec:
  replicas: 2
  selector:
    matchLabels:
      app: deploy-demo
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: deploy-demo
    spec:
      containers:
        - image: tiago-test:latest
          name: deploy-demo-container
          imagePullPolicy: Never
          resources: {}
          env:
            - name: DEPLOY_TYPE
              value: ${DEPLOY_TYPE}
          ports:
            - name: web
              containerPort: 80
              protocol: TCP
status: {}
