apiVersion: apps/v1
kind: Deployment
metadata:
  name: rolling-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      name: web-container
      app: rolling-app
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: rolling-app
        name: web-container
    spec:
      containers:
        - image: $ECR_REPO:$IMAGE_TAG
          name: web-container
          imagePullPolicy: Always
          resources: {}
          env:
            - name: DEPLOY_TYPE
              value: rolling
            - name: DEPLOY_COLOR
              value: white
            - name: COMMIT_VERSION
              value: ${IMAGE_TAG}
          ports:
            - name: web
              containerPort: 80
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: 80
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 10
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: demo-rolling-lb
  labels:
    app: app
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: web
  selector:
    name: web-container
    app: rolling-app
