apiVersion: v1
kind: Service
metadata:
  name: ok-lb
  labels:
    app: ok-app
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: web
  selector:
    name: web-container
    app: ok-app
