apiVersion: v1
kind: Service
metadata:
  name: demolb
  labels:
    app: blue-app
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: web
  selector:
    app: blue-app
