apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.appName }}-{{ .Values.appEnvironment }}-service"
  labels:
    app: "{{ .Values.appName }}-{{ .Values.appEnvironment }}"
spec:
  type: NodePort
  ports:
    - port: { { .Values.container_port |int } }
      targetPort: { { .Values.container_port |int } }
  selector:
    app: "{{ .Values.appName }}-{{ .Values.appEnvironment }}"
