---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.appName }}-{{ .Values.appEnv }}-web"
  labels:
    app: "{{ .Values.appName }}-{{ .Values.appEnv }}"
spec:
  replicas: { { .Values.replicaCount } }
  selector:
    matchLabels:
      app: "{{ .Values.appName }}-{{ .Values.appEnvironment }}"
  template:
    metadata:
      labels:
        app: "{{ .Values.appName }}-{{ .Values.appEnvironment }}"
    spec:
      containers:
        - name: "{{ .Values.appName }}-{{ .Values.appEnvironment }}-web"
          image: "{{ .Values.containerImage }}:{{ .Values.appVersion }}"
          ports:
            - containerPort: { { Values.containerPort } }
          env:
            - name: "APP_ENV"
              value: "{{ .Values.appEnvironment }}"
            - name: "APP_VERSION"
              value: "{{ .Values.appVersion }}"
            - name: "COLOR"
              value: "{{ .Values.appEnvironment }}"
